services:
  - type: web
    name: ia-persona-backend
    env: docker
    repo: https://github.com/precieux06/IA-PERSONA
    branch: main
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: web
    name: ia-persona-frontend
    env: docker
    repo: https://github.com/precieux06/IA-PERSONA
    branch: main
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
