services:
  - type: web
    name: multimodal-backend
    env: docker
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: multimodal-frontend
    env: docker
    rootDir: frontend
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://multimodal-backend.onrender.com
        
