databases:
  - name: ia-multimodale-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: ia-multimodale-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # ⚠️ à remplir manuellement sur Render
      - key: DATABASE_URL
        fromDatabase:
          name: ia-multimodale-db
          property: connectionString

  - type: web
    name: ia-multimodale-frontend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://ia-multimodale-backend.onrender.com
        
